### ISSUE TITLE
cassandra-driver-core 3.1.x is incompatible with Guava 20.0

### ISSUE THREAD

**Issue by Emmenemoi** [spring-io/platform#524] opened 2017-02-22 17:02 UTC
Needs GUAVA 16 according to its own deps, because of missing com/google/common/util/concurrent/FutureFallback after guava 19.
Guava dep seems to be ok if downgraded to 19.0 instead of 20.

**Comment by wilkinsona** [comment] 2017-02-22 17:13
Gah. Guava is a bit of a liability unfortunately. Given it's frequent breaking API changes, I really wish libraries would jar jar and embed it.

I'll need to see if there's anything that needs 20.0 before we can consider a downgrade. Your best bet for now, and perhaps longer term, is to override `guava.version` to meet your need.

**Comment by wilkinsona** [comment] 2017-02-22 17:45
On closer inspection, FutureCallback is in Guava 20.0: http://google.github.io/guava/releases/20.0/api/docs/com/google/common/util/concurrent/FutureCallback.html. Perhaps you have a corrupted jar in your Maven or Gradle cache?

**Comment by wilkinsona** [comment] 2017-02-22 18:06
And `cassandra-driver-core` doesn't depend on Guava, either directly or transitively.

Can you please clarify what the problem is?

**Comment by Emmenemoi** [comment] 2017-02-22 18:29
https://mvnrepository.com/artifact/com.datastax.cassandra/cassandra-driver-core/3.1.3 shows guava 16.0 dep.
I'm talking about Future**F**allback ;)

**Comment by wilkinsona** [comment] 2017-02-22 18:33
Oops, sorry. That's what I get for trusting Eclipse's view of the dependency hierarchy. It would also help if I could read the difference between an `F` and a `C`.

**Comment by wilkinsona** [comment] 2017-02-22 18:42
This is going to be fixed in version 3.2.0 of the driver:

 - https://datastax-oss.atlassian.net/browse/JAVA-1328
 - https://github.com/datastax/java-driver/pull/784

That opens up the option of waiting for that rather than downgrading Guava

**Comment by Emmenemoi** [comment] 2017-02-23 18:48
For the documentation : works well with Guava 19.0.

**Comment by wilkinsona** [comment] 2017-03-05 22:20
Thanks for trying 19.0.

I think we're going to have to document this as, unfortunately, it's impossible to select a version of Guava that will work for everyone. In researching this issue, I've learned that Selenium's remote driver recently upgraded to Guava 21.0 which requires Java 8. That's not an option for the Platform at the moment as Brussels supports also supports Java 7.

Spring Framework 4.3.x compiles against Guava 20.0 so that feels like the most sensible version for the Platform to provide. I'll update the documentation with a section about Guava explaining the problem and linking to the sections on overriding a dependency's version.

**Comment by wilkinsona** [comment] 2017-03-06 09:07
Selenium's remote driver didn't upgrade to Guava 21.0 until its 2.23.1 release (worryingly, 2.32.0 uses 19.0 so that's a jump from 19.0 to 21.0 in a 0.0.x release). Brussels uses 2.21 so it's not actually  a concern in the Brussels release line.

I think there's only really two choices here that are even somewhat viable:

1. Align the Platform's version of Guava with what the various Spring projects build against
2. Make an exception for Guava and remove its dependency management from the Platform

The downside of 1 is that it causes problems such as the one reported here. The downside of 2 is that it may require people to pick the version of Guava themselves if a transitive dependency isn't already "picking" a version for them.

1 isn't an option for Brussels. We should consider 2 for Cairo.

**Closed** 2017-03-07 10:34 UTC
Labels: documentation

**Comment by szabelin** [comment] 2017-08-08 12:24
It is quite a disappointment that Guava is unusable for the new Streams and Graphs and other things that have been added because we have no choice now but using DataStax, and DataStax decided to stay on old version. DataStax is a library, designers should be conscious of this really

**Comment by wilkinsona** [comment] 2017-08-08 12:28
I share your disappointment, but commenting on it here isn't going to change anything. I believe that the problem was going to be fixed in 3.2 of the Cassandra Driver. If that's not the case then you may want to raise it with the Cassandra Driver team. Only they can change how the use Guava.

**Comment by szabelin** [comment] 2017-08-08 12:34
They haven't:
https://mvnrepository.com/artifact/com.datastax.cassandra/cassandra-driver-core/3.3.0

Thanks, will raise with them

**Comment by wilkinsona** [comment] 2017-08-08 12:37
Please read the issues that I [linked to above](https://github.com/spring-io/platform/issues/524#issuecomment-281761625) before raising anything with the Cassandra Driver team. The presence of the dependency alone doesn't mean that the problem has not been fixed. As I understand it, they were going to ensure that the driver was compatible with a range of Guava versions rather than removing the dependency altogether.

**Comment by szabelin** [comment] 2017-08-08 12:42
great, I'll give it a try, thanks a lot.
