### ISSUE TITLE
Override spring-boot.version

### ISSUE THREAD

**Issue by Robin7Ma** [spring-io/platform#414] opened 2016-08-09 07:28 UTC
Current Spring Boot(1.3.7.RELEASE) has a bug, the new version(1.4.0.RELEASE) already fixed it. but the latest platform-bom is extend from spring-boot 1.3.7.RELEASE , Can I override it to 1.4.0.RELEASE? How can I do this?

Thank you!

**Comment by wilkinsona** [comment] 2016-08-09 07:40
You cannot, by design, override the version of Spring Boot. If you want to use a Spring Boot 1.4-based version of the Platform, you should use Athens RC1: https://spring.io/blog/2016/07/29/spring-io-platform-athens-rc1

Out of interest, what's the bug in Spring Boot 1.3.7 that you believe is fixed in 1.4.0? 1.3.7 and 1.4.0 were released at the same time so they should contain the same bug fixes.

**Comment by Robin7Ma** [comment] 2016-08-09 08:00
I'm sorry, maybe the "bug" is because my Spring is too new (4.3.x), in this version, `ResourceHttpRequestHandler` class has changed, and then `LogFileMvcEndpoint` cannot work.

I will try to return all version to io-platform default, thank you!

**Comment by wilkinsona** [comment] 2016-08-09 08:27
> ResourceHttpRequestHandler class has changed, and then LogFileMvcEndpoint cannot work.

There shouldn't have been any backwards incompatible changes made to `ResourceHttpRequestHandler` in Spring Framework 4.3. If you've found one, please [open a JIRA ticket](https://jira.spring.io/browse/SPR).

**Closed by wilkinsona** 2016-08-09 08:27 UTC

**Comment by Robin7Ma** [comment] 2016-08-09 09:12
I think it's Spring-Boot's issue, because `ResourceHttpRequestHandler` is a "InitializingBean", it means if you `new` bean without spring context,  you should call `afterPropertiesSet` method to init something.

But before spring-boot v1.4.x,  `LogFileMvcEndpoint` didn't call  `afterPropertiesSet` after new a `ResourceHttpRequestHandler` subclass named `Handler`.

In spring-boot v1.4.0.RELEASE, It changed to this:

```Java
	private static class Handler extends ResourceHttpRequestHandler {
		private final Resource resource;
		Handler(Resource resource) {
			this.resource = resource;
			try {
				// Look here
				afterPropertiesSet();
			}
			catch (Exception ex) {
				throw new IllegalStateException(ex);
			}
		}
	// Other codes ...
	}
```

**Comment by wilkinsona** [comment] 2016-08-09 09:27
Thanks. I've opened https://github.com/spring-projects/spring-boot/issues/6592 so that we can consider back porting the change to 1.3.x.

**Comment by Robin7Ma** [comment] 2016-08-09 09:34
OK, I think you should sleep, good night!
